on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@v2.3
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN_COREFLUXPROD }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          ado_organization: "CorefluxProd"
          ado_project: "BrokerAndHub"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
